# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b15d8216dfdf1aa624d41fc5cdf6c747"
name = "admin-order-test"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
dev_store_url = "cql-checkout-extend.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,read_products"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
