# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e786543e2eb1b3457e0b52ca21bfc308"
name = "delivery-method"
handle = "delivery-method-4"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
dev_store_url = "cql-checkout-extend.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
