# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e83b1ad83b128b804d2f56505bba43ae"
name = "checkout-delivery-date"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
dev_store_url = "cql-checkout-extend.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
