# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "dynamic-extension-test-eddie"
client_id = "960c400817131bbb75d5ca0281bb9aa7"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false

[build]
dev_store_url = "cql-checkout-extend.myshopify.com"
