# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a358df1b400b06a724d0743957810e20"
name = "admin-test-2"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
include_config_on_deploy = true

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
