# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "shawn-compare-at-price"
client_id = "f117002093072922e677d10c9ec16a4d"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false

[build]
dev_store_url = "cql-onboarding.myshopify.com"
